target 'Twitter'
platform :ios, '9.0'

pod 'Mantle'
pod 'KVNProgress'
pod 'NSHash'
pod 'SDWebImage'
pod 'SKSplashView'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'DZNEmptyDataSet'
pod 'GGFullscreenImageViewController'
pod 'VGParallaxHeader'
